### ISSUE TITLE
Je live linkje werkt niet :)

### ISSUE THREAD

**Issue by KrijnHoetmer** [reyrey-https/your-tribe-profile-card#4]
Kijk nog even naar [de instructies van maandag](https://github.com/fdnd-task/your-tribe-profile-card/blob/main/docs/visitekaartje-ontwerpen-maken-en-online-publiceren.md#1-url-toevoegen-aan-de-repository) hoe je dat kunt oplossen.

**Comment by reyrey-https** [comment]
Opgelost :)
